
interface _GlobalComponents {
      'AdminHeader': typeof import("../components/AdminHeader.vue")['default']
    'AdminSideBar': typeof import("../components/AdminSideBar.vue")['default']
    'ChartCategoryByProduct': typeof import("../components/ChartCategoryByProduct.vue")['default']
    'ChartCustomer': typeof import("../components/ChartCustomer.vue")['default']
    'ChartSaleProduct': typeof import("../components/ChartSaleProduct.vue")['default']
    'ConfirmModal': typeof import("../components/ConfirmModal.vue")['default']
    'DemoChart': typeof import("../components/DemoChart.vue")['default']
    'Loader': typeof import("../components/Loader.vue")['default']
    'ModalPos': typeof import("../components/ModalPos.vue")['default']
    'TableCategory': typeof import("../components/TableCategory.vue")['default']
    'TableCustomer': typeof import("../components/TableCustomer.vue")['default']
    'TableOrder': typeof import("../components/TableOrder.vue")['default']
    'TablePos': typeof import("../components/TablePos.vue")['default']
    'TableProduct': typeof import("../components/TableProduct.vue")['default']
    'TableReportSaleProduct': typeof import("../components/TableReportSaleProduct.vue")['default']
    'TableSale': typeof import("../components/TableSale.vue")['default']
    'TableSubCategory': typeof import("../components/TableSubCategory.vue")['default']
    'TableUser': typeof import("../components/TableUser.vue")['default']
    'Test': typeof import("../components/Test.vue")['default']
    'TestModal': typeof import("../components/TestModal.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAdminHeader': typeof import("../components/AdminHeader.vue")['default']
    'LazyAdminSideBar': typeof import("../components/AdminSideBar.vue")['default']
    'LazyChartCategoryByProduct': typeof import("../components/ChartCategoryByProduct.vue")['default']
    'LazyChartCustomer': typeof import("../components/ChartCustomer.vue")['default']
    'LazyChartSaleProduct': typeof import("../components/ChartSaleProduct.vue")['default']
    'LazyConfirmModal': typeof import("../components/ConfirmModal.vue")['default']
    'LazyDemoChart': typeof import("../components/DemoChart.vue")['default']
    'LazyLoader': typeof import("../components/Loader.vue")['default']
    'LazyModalPos': typeof import("../components/ModalPos.vue")['default']
    'LazyTableCategory': typeof import("../components/TableCategory.vue")['default']
    'LazyTableCustomer': typeof import("../components/TableCustomer.vue")['default']
    'LazyTableOrder': typeof import("../components/TableOrder.vue")['default']
    'LazyTablePos': typeof import("../components/TablePos.vue")['default']
    'LazyTableProduct': typeof import("../components/TableProduct.vue")['default']
    'LazyTableReportSaleProduct': typeof import("../components/TableReportSaleProduct.vue")['default']
    'LazyTableSale': typeof import("../components/TableSale.vue")['default']
    'LazyTableSubCategory': typeof import("../components/TableSubCategory.vue")['default']
    'LazyTableUser': typeof import("../components/TableUser.vue")['default']
    'LazyTest': typeof import("../components/Test.vue")['default']
    'LazyTestModal': typeof import("../components/TestModal.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AdminHeader: typeof import("../components/AdminHeader.vue")['default']
export const AdminSideBar: typeof import("../components/AdminSideBar.vue")['default']
export const ChartCategoryByProduct: typeof import("../components/ChartCategoryByProduct.vue")['default']
export const ChartCustomer: typeof import("../components/ChartCustomer.vue")['default']
export const ChartSaleProduct: typeof import("../components/ChartSaleProduct.vue")['default']
export const ConfirmModal: typeof import("../components/ConfirmModal.vue")['default']
export const DemoChart: typeof import("../components/DemoChart.vue")['default']
export const Loader: typeof import("../components/Loader.vue")['default']
export const ModalPos: typeof import("../components/ModalPos.vue")['default']
export const TableCategory: typeof import("../components/TableCategory.vue")['default']
export const TableCustomer: typeof import("../components/TableCustomer.vue")['default']
export const TableOrder: typeof import("../components/TableOrder.vue")['default']
export const TablePos: typeof import("../components/TablePos.vue")['default']
export const TableProduct: typeof import("../components/TableProduct.vue")['default']
export const TableReportSaleProduct: typeof import("../components/TableReportSaleProduct.vue")['default']
export const TableSale: typeof import("../components/TableSale.vue")['default']
export const TableSubCategory: typeof import("../components/TableSubCategory.vue")['default']
export const TableUser: typeof import("../components/TableUser.vue")['default']
export const Test: typeof import("../components/Test.vue")['default']
export const TestModal: typeof import("../components/TestModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAdminHeader: typeof import("../components/AdminHeader.vue")['default']
export const LazyAdminSideBar: typeof import("../components/AdminSideBar.vue")['default']
export const LazyChartCategoryByProduct: typeof import("../components/ChartCategoryByProduct.vue")['default']
export const LazyChartCustomer: typeof import("../components/ChartCustomer.vue")['default']
export const LazyChartSaleProduct: typeof import("../components/ChartSaleProduct.vue")['default']
export const LazyConfirmModal: typeof import("../components/ConfirmModal.vue")['default']
export const LazyDemoChart: typeof import("../components/DemoChart.vue")['default']
export const LazyLoader: typeof import("../components/Loader.vue")['default']
export const LazyModalPos: typeof import("../components/ModalPos.vue")['default']
export const LazyTableCategory: typeof import("../components/TableCategory.vue")['default']
export const LazyTableCustomer: typeof import("../components/TableCustomer.vue")['default']
export const LazyTableOrder: typeof import("../components/TableOrder.vue")['default']
export const LazyTablePos: typeof import("../components/TablePos.vue")['default']
export const LazyTableProduct: typeof import("../components/TableProduct.vue")['default']
export const LazyTableReportSaleProduct: typeof import("../components/TableReportSaleProduct.vue")['default']
export const LazyTableSale: typeof import("../components/TableSale.vue")['default']
export const LazyTableSubCategory: typeof import("../components/TableSubCategory.vue")['default']
export const LazyTableUser: typeof import("../components/TableUser.vue")['default']
export const LazyTest: typeof import("../components/Test.vue")['default']
export const LazyTestModal: typeof import("../components/TestModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
